### ISSUE TITLE
Release latest changes?

### ISSUE THREAD

**Issue by randycoulman** [tuvistavie/ex_cli#4]
Thanks for this library!  It's just what I needed for a little learning project I'm working on!

When you have time, could you please release a new version that has the latest fixes included?  I'm seeing the warnings that were addressed in 8175d9cf0b061debae2096f26925a4a3a433e21b.

Thanks!

**Comment by tuvistavie** [comment]
Hi, I just published this as version 0.1.1 :smile:

**Comment by randycoulman** [comment]
Awesome, thanks!
