### ISSUE TITLE
Allow usage of a name with dot

### ISSUE THREAD

**Issue by wende** [tuvistavie/ex_cli#8]
Great package!

I think it'd be really nice if this was possible
```
use ExCLI.DSL, mix_task: :'mytask.install'
```
So it conformed to mix command rules (like 'mix deps.get' 'mix coveralls.detail' etc)

**Comment by tuvistavie** [comment]
Hi, thanks for reporting.
I just fixed this issue and published a new version to hex.
It should now work properly, but let me know if you run into any trouble.
Thank you.
